<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function count ()
    {
        $q = $this->createQueryBuilder('p');

        $q->select('COUNT(p.image_path)');
        return $q->getQuery()->getSingleScalarResult();
    }

    public function retrievePost(){
        $q = $this->createQueryBuilder('p');
     
     return $q->select('p.title, p.image_path')
                ->getQuery()
                ->getResult(Query::HYDRATE_ARRAY);

    }
    
    
    public function  findAll()
    {
        return $this->findBy(array(), array('created' => 'DESC'));
    }
}
